server:
  port: 8080
spring:
  application:
    name: springboot-minio
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  data:
    mongodb:
<<<<<<< HEAD
      uri: mongodb://adminUser:adminPassword@localhost/cms_db?authSource=admin
      database: don
      auto-index-creation: false
#      host : localhost
=======
#      uri: mongodb+srv://iamdon123:iamdon123@filedetails.7iehtdf.mongodb.net/don?retryWrites=true&w=majority
>>>>>>> b07b2961318313193ce07bc6bf0d5b06614562c6
#      database: don
#      auto-index-creation: false
      host : localhost
      database: don
      port: 27018

javers:
    documentDbCompatibilityEnabled: false
    objectAccessHook: org.javers.spring.mongodb.DBRefUnproxyObjectAccessHook
    snapshotsCacheSize: 5000
    snapshotCollectionName: "Audit_table"
    headCollectionName: "commit_id"
    schemaManagementEnabled: true

minio:
  endpoint: http://127.0.0.1:9000
  port: 9000
  accessKey: minioadmin #Login Account
  secretKey: minioadmin # Login Password
  secure: false
  bucket-name: testbucket # Bucket Name
  image-size: 20971520 #  Maximum size of picture file
  file-size: 20971520 #  Maximum file size



